### ISSUE TITLE
Front-end developer filter not working

### ISSUE THREAD

**Issue by erfan-goodarzi** [p3yman/tech-immigrants-archive#1]
## Issue Title
The Front-end developer filter not working.

## Issue Description
The "front-end developer" filter is not displaying any results, despite having 4 videos that contain front-end title

## Expected Behavior
The "front-end developer" filter should display all videos that have been tagged with "front-end" in the system.

**Comment by p3yman** [comment]
Hey Erfan, thanks for the issue. Not all the data has been entered and it's a WIP.

**Comment by erfan-goodarzi** [comment]
Okay then. Great. If there is any task or something else I'd like to help.

**Comment by p3yman** [comment]
The main thing we need right now is completing the data on the videos. Please read the `README.md` file and make pull requests for updating the data. Just remember make smaller PRs as others maybe also working on updating and we want to pass any conflicts on PRs. Thank you in advance.
